### PR TITLE
Mappers can be directly injected.

### PR DESCRIPTION
**Pull request by emacarron**
Hi Elizabeth,

I saw your MyBatis sample at twitter. It looks really great.

This PR is just o point that when using mybatis with spring you can inject a mapper directly into your service. This is probably the strongest point of the spring integration of mybatis. This is the only tool that I am aware of that lets you build you app with no imports to it.

Have a good day!

### CODE REVIEW

**Comment by elizabetht** [comment]
Thanks @emacarron for taking your time to modify my code and for this important pointer.  Much appreciated!

**Comment by elizabetht** [comment]
Eduardo (@emacarron), could you also let me know how you found the blog link from the flurry of tweets? This would help me to propagate my blog to the correct audience.

**Comment by emacarron** [comment]
Hi. I was searching for an old mybatis tweet. I saw yours and had a look at your sample.

**Comment by elizabetht** [comment]
Thanks @emacarron

**Pull request merged**
